# Generated by Django 3.2.7 on 2022-04-30 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_item', models.CharField(max_length=200)),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lists.listname')),
            ],
        ),
    ]
